# Generated by Django 4.0.5 on 2022-06-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screener', models.TextField(blank=True, null=True)),
                ('exchange', models.TextField(blank=True, null=True)),
                ('symbol', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
